# file: molecule.yml
---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  # - name: instance
  #   image: "geerlingguy/docker-ubuntu2004-ansible:latest"
  # - name: instance
  #   image: "geerlingguy/docker-ubuntu2204-ansible:latest"
  # - name: instance
  #   image: "geerlingguy/docker-ubuntu2404-ansible:latest"
  # - name: instance
  #   image: "geerlingguy/docker-fedora37-ansible:latest"
  # - name: instance
  #   image: "geerlingguy/docker-fedora38-ansible:latest"
  # - name: instance
  #   image: "geerlingguy/docker-fedora39-ansible:latest"
  # - name: instance
  #   image: "geerlingguy/docker-fedora40-ansible:latest"
  # - name: instance
  #   image: "geerlingguy/docker-fedora39-ansible:latest"
  # - name: instance
  #   image: "geerlingguy/docker-fedora41-ansible:latest"
  # - name: instance
  #   image: "chriswayg/docker-archlinux-ansible:latest"
  - name: instance
    image: "geerlingguy/docker-fedora40-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    prepare: prepare.yml
  config_options:
    defaults:
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/../..
      gather_timeout: 30
  inventory:
    host_vars:
      instance:
        ansible_become_method: sudo
        ansible_become_password: ""
verifier:
  name: ansible
