---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Get headers of the URL
      ansible.builtin.uri:
        url: "https://download.live.ledger.com/latest/linux"
        method: GET
        validate_certs: true
        return_content: false
      register: url_headers

    - name: Define search pattern
      ansible.builtin.set_fact:
        search_pattern: "https://download.live.ledger.com/ledger-live-desktop-(.*?)-linux-x86_64.AppImage"

    - name: Define replacement pattern
      ansible.builtin.set_fact:
        replace_pattern: "https://download.live.ledger.com/ledger-live-desktop-(.*?)-linux-x86_64.AppImage"

    - name: Extract version number from URL
      ansible.builtin.set_fact:
        ledger_live_version: "{{ url_headers.url | regex_search(search_pattern) | regex_replace(replace_pattern, '\\1') | safe }}"

    - name: Check if Ledger Live AppImage exists
      ansible.builtin.stat:
        path: "/opt/ledger-live-desktop-{{ ledger_live_version }}-linux-x86_64.AppImage"
      register: appimage_file

    - name: Assert AppImage exists and is executable
      ansible.builtin.assert:
        that:
          - appimage_file.stat.exists
          - appimage_file.stat.mode == '0775'

    - name: Check if icon exists
      ansible.builtin.stat:
        path: "/opt/ledgerliveicon.png"
      register: icon_file

    - name: Assert icon exists
      ansible.builtin.assert:
        that:
          - icon_file.stat.exists

    - name: Check if desktop file exists
      ansible.builtin.stat:
        path: "/usr/share/applications/ledgerlive.desktop"
      register: desktop_file

    - name: Assert desktop file exists
      ansible.builtin.assert:
        that:
          - desktop_file.stat.exists

    - name: Check if udev rules script exists
      ansible.builtin.stat:
        path: "/tmp/add_udev_rules.sh"
      register: udev_script

    - name: Assert udev rules script exists
      ansible.builtin.assert:
        that:
          - udev_script.stat.exists
